group: edge
sudo: required
language: python
os: linux
dist: trusty
python:
  - 3.6
node_js:
  - node
matrix:
  include:
    - env: INFO="lint"
    - addons:
        chrome: beta
      env: INFO="chrome beta" BROWSER=google-chrome-beta ENABLE_XVFB=1
    - addons:
        chrome: stable
      env: INFO="chrome stable" BROWSER=google-chrome-stable ENABLE_XVFB=1
    - addons:
        firefox: latest-dev
      env: INFO="firefox dev" BROWSER=firefox ENABLE_XVFB=1
    - addons:
        firefox: latest-nigtly
      env: INFO="firefox nightly" BROWSER=firefox ENABLE_XVFB=1
    - addons:
        firefox: latest-unsigned
      env: INFO="firefox unsigned" BROWSER=firefox ENABLE_XVFB=1
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_script: . ./scripts/setup_travis.sh
script: . ./scripts/run_travis.sh
